spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://postgresql_db:5432/master
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
jwt:
  secret: ${JWT_SECRET:ZG9ja2VyU2VjcmV0S2V5VGhhdElzTG9uZ0Vub3VnaEZvckhlYXZlbnNTYWtl}
frontend:
  url: http://localhost:4200
server:
  port: 8080