spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/master
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  devtools:
    restart:
      enabled: true
frontend:
  url: http://localhost:4200
jwt:
  secret: ZGV2T25seVNlY3JldEtleVRoYXRJc0xvbmdFbm91Z2hGb3JIZWF2ZW5zU2FrZQ==
server:
  port: 8080